### ISSUE TITLE
Data External

### ISSUE THREAD

**Issue by zCastleM** [chaibuilder/nextjs#3]
![image](https://github.com/chaibuilder/nextjs/assets/116334877/1ece19f8-f621-45e0-a5df-152c92cd7583)
How can I connect external data, it doesn't appear in the admin?

**Comment by surajair** [comment]
External data needs to be fetched using the `registerDataProvider` function. Its similar to how getStaticProps() works in nextJS

**Comment by zCastleM** [comment]
Can you give me an example of how I can do this?

**Comment by surajair** [comment]
@zCastleM 
You need to enable `dataBindingSupport={true}` to enable this feature. 
add the above prop to `app/admin/page.tsx`
`return <ChaiBuilderStudio dataBindingSupport={true} logo={Logo} />;`

You can than choose the data provider from the `Data` tab
![capture-2024-06-28-16 51 07](https://github.com/chaibuilder/nextjs/assets/9153560/4a59fea0-95ab-4cf0-bf7c-4cbbbeaefc15)

Please refer to this file to register a custom data=provider
`https://github.com/chaibuilder/nextjs/blob/main/data-providers/default.ts`

**Comment by zCastleM** [comment]
@comet-rover 
![image](https://github.com/chaibuilder/nextjs/assets/116334877/ad1ce02e-b1e6-463e-8e3c-b99fd09096a7)
![image](https://github.com/chaibuilder/nextjs/assets/116334877/28376257-c6ce-4b3a-bd81-caf1ad094e77)
Hello, I made these changes, but it still doesn't work.

**Comment by comet-rover** [comment]
Please try upgrading chai builder sdk to 1.2.22

**Comment by zCastleM** [comment]
thanks!
